HW-02
vikibell/prjctr-golang-beginning pull request #1
Opened 2024-08-12 16:20 UTC by vikibell

2024-08-13 18:04 UTC, alexandear requested changes
Трішки доробити.

2024-08-13 18:04 UTC, alexandear commented on gocourse02/zoo.go
> +type Cage struct {
В умові задачі є "Треба використати щонайменше: nil". Чи можемо ми до структури клітки додати поле `Animal *Animal`? Це поле буде `nil`, якщо клітка пуста.

2024-08-13 18:04 UTC, alexandear commented on gocourse02/zoo.go
> +type Animal struct {
Додаймо тваринам можливість розмножуватись, як сказано умові задачі.

2024-08-16 08:45 UTC, vikibell commented on gocourse02/zoo.go
> +	State string
Виправила

2024-08-16 08:45 UTC, vikibell commented on gocourse02/zoo.go
> +type Cage struct {
Виправила

2024-08-16 09:15 UTC, vikibell commented on gocourse02/zoo.go
> +type Animal struct {
Додала

2024-08-16 09:42 UTC, alexandear commented on gocourse02/main.go
> +	cageBeaver := &Cage{ID: 2, State: "close"}
тут бажано використовувати константи, які задефайнені
```suggestion
	cageTiger := &Cage{ID: 1, State: stateClose}
	cageCoyote := &Cage{ID: 2, State: stateClose}
	cageBeaver := &Cage{ID: 2, State: stateClose}
```

2024-08-16 09:43 UTC, alexandear approved these changes
LGTM

2024-08-16 09:51 UTC, merged