HW-17
vikibell/prjctr-golang-beginning pull request #11
Opened 2024-10-13 18:24 UTC by vikibell

2024-10-14 12:35 UTC, alexandear requested changes

2024-10-14 12:35 UTC, alexandear commented on gocourse17/server/server_test.go
Тести фейляться, якщо запускати їх кілька разів.

<details><summary>Details</summary>
<p>


```
❯ go test -count=1 -race -v -shuffle=on -failfast -parallel 4 ./...
-test.shuffle 1728908761167764000
=== RUN   TestSendReview
--- PASS: TestSendReview (0.00s)
=== RUN   TestGetHistory
    server_test.go:60: GetHistory(): got = [cargo_state:1 service_quality:2 fulfillment_speed:3 cargo_state:1 service_quality:2 fulfillment_speed:3], want [cargo_state:1 service_quality:2 fulfillment_speed:3]
--- FAIL: TestGetHistory (0.00s)
FAIL
FAIL    github.com/vikibell/prjctr-golang-beginning/gocourse17/server   0.308s
FAIL
❯ go test -count=1 -race -v -shuffle=on -failfast -parallel 4 ./...
-test.shuffle 1728908763371430000
=== RUN   TestGetHistory
--- PASS: TestGetHistory (0.00s)
=== RUN   TestSendReview
--- PASS: TestSendReview (0.00s)
PASS
ok      github.com/vikibell/prjctr-golang-beginning/gocourse17/server   1.313s
```

</p>
</details>

2024-10-14 12:35 UTC, alexandear commented on gocourse17/server/server_test.go
Підозрюю, що проблема в тому, що тести викори стовують один і той самий `grpc.Server` в `init()`.

2024-10-14 12:35 UTC, alexandear commented on gocourse17/grpcapi/api.proto
> +  int32 fulfillment_speed = 3;
Значення оцінок обмежені, пропоную задекларувати та використати enum для оцінок.

Почитати тут https://protobuf.dev/programming-guides/enum/

Значення оцінок можна підглянути в платформі Проджектора:
<img width="420" alt="image" src="https://github.com/user-attachments/assets/1002b873-cbb2-4055-94a7-aebdad54ad38">

2024-10-14 12:35 UTC, alexandear commented on gocourse17/server/server.go
> +		return &pb.HistoryResponse{}, errors.New("invalid driver id")
Можна просто `nil` замість `&pb.HistoryResponse{}`.
```suggestion
		return nil, errors.New("invalid driver id")
```

2024-10-14 12:35 UTC, alexandear commented on gocourse17/server/server.go
> +		return &pb.HistoryResponse{}, errors.New("invalid driver id")
Замість `errors.New("invalid driver id")` пропоную використати gRPC статус коди.

Почитати тут:

- https://grpc.io/docs/guides/error/
- https://github.com/grpc/grpc-go/tree/master/examples/features/error_handling
- https://github.com/grpc/grpc-go/tree/master/examples/features/error_details

2024-10-14 12:35 UTC, alexandear commented on gocourse17/server/server.go
> +		return &pb.HistoryResponse{}, errors.New("there is no history for this driver")
В загальному це нормально, коли немає історії. Не думаю, що треба повертати помилку.

2024-10-14 12:35 UTC, alexandear commented on gocourse17/service/review.go
> +func (rh ReviewHistory) GerReviews(driverId int32) ([]Review, bool) {
```suggestion
func (rh ReviewHistory) GetReviews(driverID int32) ([]Review, bool) {
```

2024-10-14 12:35 UTC, alexandear commented on gocourse17/service/review.go
> +func NewReview(cs, sq, fs int32) Review {
Це бізнес шар, тому замість `int32` краще `int`.

Це вже на proto транспортному рівні використовують `int32`.

2024-10-14 12:35 UTC, alexandear commented on gocourse17/service/review.go
> +	return rating >= 1 && rating <= 5
Замість `1, 2, 3, 4, 5` краще використовувати константи.

2024-10-14 12:35 UTC, alexandear commented on gocourse17/service/review_test.go
> +	driverId := int32(1)
```suggestion
	driverID := int32(1)
```

https://go.dev/wiki/CodeReviewComments#initialisms

2024-10-16 16:02 UTC, vikibell commented on gocourse17/grpcapi/api.proto
> +message ReviewData {
Тут виникає конфлікт з Review структурою, як його хендлити?

2024-10-16 16:09 UTC, vikibell commented on gocourse17/client/client.go
> +		fmt.Printf("client.SendReview failed: %v\n", err)
Ним замнити також в тих місцях де юзаеться просто "log" і взагалі на нього замінити "log"

2024-10-17 10:48 UTC, alexandear requested changes

2024-10-17 10:48 UTC, alexandear commented on gocourse17/grpcapi/api.proto
> +  EXCELLENT = 5;
В цілому вірно. Можна ще трішки покращити згідно https://protobuf.dev/programming-guides/style/#enums:
```suggestion
  RATING_UNSPECIFIED = 0;
  RATING_POOR = 1;
  RATING_FAIR = 2;
  RATING_GOOD = 3;
  RATING_GREAT = 4;
  RATING_EXCELLENT = 5;
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/grpcapi/api.proto
> +message ReviewData {
Можна назвати сервер `Reviewer` по аналогії з `Greeter` в https://grpc.io/docs/languages/go/quickstart/

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server.go
> +	driverId := int(request.GetDriverId())
```suggestion
	driverID := int(request.GetDriverId())
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server.go
> +	var response []*pb.ReviewData
📝 Зазвичай, коли відома довжина слайсу, в який копіюємо, то пишуть так:
```suggestion
	response := make([]*pb.ReviewData, 0, len(history))
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server.go
> +	history, _ := s.history.GerReviews(driverId)
Підкажи, чому ігнорується другий аргумент? Якщо він не потрібен ніде, то можемо його не повертати.

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server.go
> +	history, _ := s.history.GerReviews(driverId)
Чому `GerReviews`? Може `GetReviews` або `Reviews`?

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server.go
> +		response = append(response, &pb.ReviewData{
📝 
```suggestion
		reviews = append(reviews, &pb.ReviewData{
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server.go
> +		return &pb.SendReviewResponse{Message: "Fail"}, status.Errorf(codes.InvalidArgument, "invalid driver id")
Не потрібно повертати ніякий респонс, якщо помилка. Вистачає:
```suggestion
		return nil, status.Errorf(codes.InvalidArgument, "invalid driver id")
```

Для помилки меседж зашифрований в `status.Errorf`.

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server.go
> +		return &pb.SendReviewResponse{Message: "Fail"}, status.Errorf(codes.InvalidArgument, "invalid driver id")
`Error` замість `Errorf`, бо немає форматування:
```suggestion
		return nil, status.Error(codes.InvalidArgument, "invalid driver id")
```

`Errorf` потрібно, якби:

```go
		return nil, status.Errorf(codes.InvalidArgument, "invalid driver id=%d", driverID)
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/grpcapi/api.proto
Здається, цей файл варто в `api` директорію поміщати.

https://github.com/golang-standards/project-layout/tree/master/api

2024-10-17 10:48 UTC, alexandear commented on gocourse17/grpcapi/api.proto
> +  Rating fulfillment_speed = 3;
Чи можливо відсилати лише інформацію про `cargo_state`, не присилаючи `service_quality` та `fulfillment_speed`? Здається по логіці та API, що ні.

2024-10-17 10:48 UTC, alexandear commented on gocourse17/service/review.go
> +}
В нас обмежений набір значень рейтингу, варто використовувати константи замість `int`:
```suggestion
type Rating int

const (
	RatingPoor Rating = iota + 1
	RatingFair
	RatingGood
	RatingGreat
	RatingExcellent
)

type Review struct {
	CargoState       Rating
	ServiceQuality   Rating
	FulfillmentSpeed Rating
}
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/service/review.go
> +}
Якщо оголосити тип для `Rating`, то можна писати ось так:
```
func (r Rating) IsValid() bool {
	return r >= RatingPoor && r <= RatingExcellent
}
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/service/review_test.go
> +func TestReviewHistory_AddGet(t *testing.T) {
Варто тестувати лише одну функцію за раз:
```suggestion
func TestReviewHistory_GetReviews(t *testing.T) {
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/service/review.go
> +func (rh ReviewHistory) GerReviews(driverID int) ([]Review, bool) {
```suggestion
func (rh ReviewHistory) GetReviews(driverID int) []Review {
```

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server_test.go
> +	client := pb.NewReviewClient(conn)
Чи можемо винести в хелпер функцію оцей код, який повторюється?

2024-10-17 10:48 UTC, alexandear commented on gocourse17/grpcapi/api.proto
> +  string message = 1;
```suggestion
```

Ось це поле пропоную видалити як зайве. Тому що воно містить завжди "Success", коли успішно, і "Fail" - якщо неуспішно. Але ж ми можемо просто аналізувати response status codes.

https://grpc.io/docs/guides/error/

2024-10-17 10:48 UTC, alexandear commented on gocourse17/server/server_test.go
> +func TestGetHistory(t *testing.T) {
Варто додати тест, який покриває кейс невірного значення driverID.

Ось ця функція пригодиться для перевірки коду `codes.InvalidArgument` https://pkg.go.dev/google.golang.org/grpc@v1.67.1/status#Code

2024-10-17 11:02 UTC, vikibell commented on gocourse17/grpcapi/api.proto
> +  Rating fulfillment_speed = 3;
@alexandear  Насправді варіантів реалізації оцінки може бути декілька. Якщо взяти з точки зору фронту наприклад. Ми можемо ван бай ван питати оцінку у користувача для кожного поінту і відправляти запит, а можемо виставити форму, де користувача і проставити оцінки одразу по всім поінтам. Мій варіант реалізації той, де ми виставляємо одразу всю форму.

2024-10-17 12:07 UTC, alexandear commented on gocourse17/grpcapi/api.proto
> +  Rating fulfillment_speed = 3;
Ти права. Хай буде вже. Я хотів, щоб ти подумала, як зробити так, щоб можна було апдейтити лише одне поле.

2024-10-21 09:50 UTC, alexandear commented on gocourse17/service/review_test.go
> +func TestIsValid(t *testing.T) {
Можна ось тут надихнутися тестами https://github.com/golangci/golangci-lint/blob/8a9cdad5a3544e16b77b6f470e57934e1e9af301/pkg/config/config_test.go#L9

Почитати https://go.dev/wiki/TableDrivenTests

2024-10-21 09:51 UTC, alexandear commented on gocourse17/service/review_test.go
> +	got := history.GetReviews(driverID)[0]
Пропущена перевірка, коли `history.GetReviews` повертає пустий слайс.

`history.GetReviews(driverID)[0]` викине паніку, якщо буде пустий слайс. Паніку навіть в тестах варто не допускати.

2024-10-21 09:52 UTC, alexandear commented on gocourse17/service/review.go
> +}
Незрозуміло, для чого конструктор, якщо всі поля експортовані.

Треба вибрати, або з конструктором:

```go
type Review struct {
	cargoState       Rating
	serviceQuality   Rating
	fulfillmentSpeed Rating
}

func NewReview(cs, sq, fs Rating) Review {
	return Review{
		cargoState:       cs,
		serviceQuality:   sq,
		fulfillmentSpeed: fs,
	}
}
```

або без конструктора:
```go
type Review struct {
	CargoState       Rating
	ServiceQuality   Rating
	FulfillmentSpeed Rating
}
```

2024-10-21 09:53 UTC, alexandear commented on gocourse17/README.md
> +# Getting started
Про README.md: https://www.makeareadme.com/

2024-10-22 09:13 UTC, merged