HW-03
vikibell/prjctr-golang-beginning pull request #2
Opened 2024-08-18 17:21 UTC by vikibell

2024-08-18 18:20 UTC, alexandear requested changes

2024-08-18 18:20 UTC, alexandear commented on gocourse03/go.mod
> +go 1.22.5
Найновіша версія Go на сьогодні `1.23.0` https://go.dev/dl/. Може оновити?

2024-08-18 18:20 UTC, alexandear commented on gocourse03/main.go
> +	"math/rand"
```suggestion
	"math/rand/v2"
```

Стаття https://go.dev/blog/randv2 пояснює, чому `math/random/v2` краще за `math/random`.

2024-08-18 18:20 UTC, alexandear commented on gocourse03/main.go
> +func getRandomSector() Sector {
Можливо, `chooseRandomSector` більш слушне ім'я функції?

2024-08-18 18:20 UTC, alexandear commented on gocourse03/mouse_city.go
> +const SectorCenter Sector = "Sector Center"
Константи різних типів бажано розділяти пустим рядком.

2024-08-18 18:20 UTC, alexandear commented on gocourse03/mouse_city.go
> +		Type      rodentType
📝  Чому `Sector` з великої літери, а `rodentType` - з маленької? Напевно, варто вже все робити експортованим для консистенції.

2024-08-18 18:20 UTC, alexandear commented on gocourse03/mouse_city.go
> +		),
Як думаєш, наскільки важко в майбутньому протестувати цей рядок?

Чи не краще передавати час `Time` як параметр `NewMovement`?

2024-08-18 18:20 UTC, alexandear commented on gocourse03/main.go
> +		{ID: 11, Type: RodentRat, History: FromTo{}, Movements: NewDailyMovements()},
Можливо, варто зробити конструктор `NewRodent` для `Rodent`?

2024-08-18 18:20 UTC, alexandear commented on gocourse03/mouse_city.go
> +	}
Спробуймо оголосити `DailyMovements` ось так
```suggestion
	DailyMovements []Movement
```
та підлаштувати решту коду під це.

Має працювати.

2024-08-18 18:20 UTC, alexandear commented on gocourse03/mouse_city.go
> +	}
Ось як тут `type Persons []Person`
https://go.dev/play/p/361NYZpFqvf

2024-08-20 10:55 UTC, vikibell commented on gocourse03/main.go
> +		{ID: 11, Type: RodentRat, History: FromTo{}, Movements: NewDailyMovements()},
З якої літери мають починатись аргументи функції конструктора?
Бо виник такий кейс:
![Screenshot_20240820_135215](https://github.com/user-attachments/assets/96f83af0-67e9-40e9-b606-30805f3c9ddc)

Пофіксити можна або аргументом Type або використати іншу назву (уникати використання зарезервованих слів)?

2024-08-20 13:00 UTC, vikibell commented on gocourse03/mouse_city.go
> +	}
Виправила

2024-08-21 12:57 UTC, alexandear requested changes

2024-08-21 12:57 UTC, alexandear commented on gocourse03/main.go
> +		"Sector A", "Sector B", "Sector C", "Sector D", "Sector E",
Я би для цих секторів теж зробив константи, як для `Sector Center`.

Просто читач бачить лише одну константу `const SectorCenter Sector = "Sector Center"
` і думатиме, що це всі можливі сектори. А ось і ніт.

2024-08-21 12:57 UTC, alexandear commented on gocourse03/main.go
> +		NewRodent(66, "To delete type", FromTo{}, NewDailyMovements()),
Ось так має працювати:
```suggestion
		NewRodent(11, RodentRat, FromTo{}, nil),
		NewRodent(12, RodentRat, FromTo{}, nil),
		NewRodent(13, RodentRat, FromTo{}, nil),
		NewRodent(66, "To delete type", FromTo{}, nil),
```

`NewDailyMovements` можна взагалі видалити.

В Go є такий принцип "Make zero value useful". https://dave.cheney.net/2013/01/19/what-is-the-zero-value-and-why-is-it-useful

В нашому випадку можемо використовувати `nil` як корисне "zero value".

2024-08-21 12:57 UTC, alexandear commented on gocourse03/main.go
> +			NewMovement(SectorCenter, sector, startMovement.Local().Add(time.Minute*time.Duration(2+rand.IntN(10)))),
А для чого було додано `.Local()`?

2024-08-21 12:57 UTC, alexandear commented on gocourse03/main.go
> +	rodents = slices.Delete(rodents, 3, 4)
Це дуже добре, що ти знаєш про `slices.Delete` ;)

Але давай вручну напишемо метод для видалення? Просто суть домашки в тому, щоб навчитись виконувати різні операції зі слайсом.

В допомогу https://go.dev/wiki/SliceTricks

2024-08-21 12:57 UTC, alexandear commented on gocourse03/main.go
> +	for key, _ := range rodents {
Спробуй, чи ось так працюватиме:
```suggestion
	for key := range rodents {
```

2024-08-21 12:59 UTC, alexandear commented on gocourse03/main.go
> +		{ID: 11, Type: RodentRat, History: FromTo{}, Movements: NewDailyMovements()},
Назви параметрів в усіх функціях (методах, конструкторах) мають бути з маленької літери завжди. Я не згадаю кейс, коли треба з великої. 

Так, уникати `type` в назві. З цим нічого не зробиш, бо зарезервоване слово.

2024-08-21 13:35 UTC, vikibell commented on gocourse03/main.go
> +		"Sector A", "Sector B", "Sector C", "Sector D", "Sector E",
Так як я створювала цю фунцію чисто для відображення, можливо є сенс просто Sector Center винести в змінну і одразу використати, а константу взагалі прибрати?

2024-08-21 14:04 UTC, vikibell commented on gocourse03/main.go
> +		"Sector A", "Sector B", "Sector C", "Sector D", "Sector E",
@alexandear

2024-08-23 14:32 UTC, alexandear commented on gocourse03/go.mod
> +go 1.23
див. https://github.com/vikibell/prjctr-golang-beginning/pull/3#discussion_r1728883505

2024-08-23 14:33 UTC, alexandear commented on gocourse03/main.go
> +	//Delete incorrect rodent
gofmt:

```suggestion
	// Delete incorrect rodent
```

2024-08-23 14:33 UTC, alexandear commented on gocourse03/main.go
> +		"Sector A", "Sector B", "Sector C", "Sector D", "Sector E",
Так, можна і константу прибрати.

2024-08-25 08:31 UTC, merged