HW-04
vikibell/prjctr-golang-beginning pull request #3
Opened 2024-08-21 14:30 UTC by vikibell

2024-08-23 14:31 UTC, alexandear requested changes
Дуже добре написані тести.

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo.go
> +func (z *Zoo) LookupAnimalByName(name string) ([]Sector, bool) {
Краще зробити, щоб функція повертала лише слайс секторів:
```suggestion
func (z *Zoo) LookupAnimalByName(name string) []Sector {
```

Таким чином, функцію краще можна буде перевикористати для різних потреб. Всі, хто викликатимуть цю функцію, зможуть перевірити чи слайс пустий. Якщо пустий, значить щось надрукувати.

Бо зараз ця функція `LookupAnimalByName` робить дві речі:
1) шукає сектори
2) виводить в stdout `Animal with name %s was not found`

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo.go
> +func (z *Zoo) LookupAnimalByID(id string) (Sector, bool) {
Можна повернути `nil`, якщо не знайдено та позбутись зайвого параметру:
```suggestion
func (z *Zoo) LookupAnimalByID(id string) *Sector {
```

Також, виводити `Animal with ID %s was not found` краще в функції, яка викликає `LookupAnimalByID`.

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo.go
> +					break loopExit
Можна обійтись без label, а відразу робити `return`. Так легше читатиметься.

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo.go
> +func MoveAnimal(sectorFrom *Sector, sectorTo *Sector, animal Animal) {
Можемо ось так:
```suggestion
func MoveAnimal(from, to *Sector, animal Animal) {
```

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	assert.True(t, ok, "Animal should exist") //Movement was not made
gofmt:
```suggestion
	assert.True(t, ok, "Animal should exist") // Movement was not made
```

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +import "github.com/stretchr/testify/assert"
Але хай вже буде testify, не переробляй.

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	assert.True(t, exists, "Sector shouldn't exist")
Не потрібно перевіряти, чи існує сектор. Тому що ми ж тестуємо саме функцію `DeleteSector`.

```suggestion
```

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	assert.True(t, exists, "Animal should exist")
Не потрібно перевіряти, чи існує тварина. Тому що ми ж тестуємо саме функцію `DeleteAnimal`.

```suggestion
	_, exists := sector.GetAnimal("animal_1")
	assert.True(t, exists, "Animal should exist")
```

Тести мають бути простими.

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	assert.True(t, exists, "Area should exist")
Тут теж перевірка не потрібна, бо тестується функція `DeleteArea`.

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	assert.Equal(t, sectorFound, sector, "Sectors should be equal")
Тут переплутані аргументи expected-actual:
```suggestion
	assert.Equal(t, sector, sectorFound, "Sectors should be equal")
```
Це важливо, тому що від цього залежить вивід тесту, який зафейлиться.

В Equal функції на першому місці `expected`, на другому - `actual` https://pkg.go.dev/github.com/stretchr/testify/assert#Equal
```go
func Equal(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool
```

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	assert.Equal(t, sectorFound, Sector{}, "Sectors should be equal")
див. попередній комент:
```suggestion
	assert.Equal(t, Sector{}, sectorFound, "Sectors should be equal")
```

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	assert.Len(t, sectorsFound, 0, "Should be 0 sectors")
Можна ось так спростити:
```suggestion
	assert.Empty(t, sectorsFound, "Sectors should be empty")
```

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	sectorTo := NewSector("sector_2", "Ducks", nil)
Можна простіше:
```suggestion
	from := NewSector("sector_1", "Parrots", NewTechnicalRoom("tr_1"))
	animal := NewAnimal("animal_1", "Frodo")

	to := NewSector("sector_2", "Ducks", nil)
```

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	animal2 := NewAnimal("animal_2", "Bilbo")
Ось так легше читатиметься:
```suggestion
	parrotsSector := NewSector("sector_1", "Parrots", nil)
	ducksSector := NewSector("sector_2", "Ducks", nil)
	frodo := NewAnimal("animal_1", "Frodo")
	bilbo := NewAnimal("animal_2", "Bilbo")
```

Змінні типу `sector1, sector2, animal1, animal2, animal3` бажано уникати навіть в тестах. Тести - це по суті, той же код. І до нього такі ж стандарти якості застосовуються.

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	animal2 := NewAnimal("animal_2", "Bilbo")
В усіх інших функціях теж бажано прибрати цифри в назвах змінних.

2024-08-23 14:31 UTC, alexandear commented on gocourse04/smart_zoo_test.go
> +	}
Можна переробити, щоб був лише один цикл `for`.

Бо зараз функція спочатку створює в циклі 90 тварин, додає їх в мапу. Далі ітерується по мапі та додає до сектору.

Можна ж відразу створити тварину, додати тварину в мапу, додати цю ж тварину в сектор.

2024-08-25 09:58 UTC, vikibell commented on gocourse04/smart_zoo.go
> +	return s, exists
Тобто тут exists має оброблятись на стороні виклику? 

func (a *Area) GetSector(id string) Sector {
	return a.Sectors[id]
}

Бо я отримую assignment mismatch далі по коду

![image](https://github.com/user-attachments/assets/475db9f5-8b26-4170-8473-36223b574fc2)

2024-08-25 12:39 UTC, alexandear requested changes
Фінальні штрихи.

2024-08-25 12:39 UTC, alexandear commented on gocourse04/smart_zoo.go
> +	return s, exists
Це я помилився. `a.Sectors[id]` може повертати два, а може один результат:

```go
s, ok := a.Sectors[id]
// або
s := a.Sectors[id]
```

Але в конструкції `return a.Sectors[id]` завжди один результат.

2024-08-25 12:39 UTC, alexandear commented on gocourse04/smartzoo_test.go
> +	assert.Equal(t, parrotsSector.ID, sectorFound.ID, "Sectors should be equal")
Якщо раптом `sectorFound` буде `nil`, то в цьому місці буде паніка, що не є гуд:

```
=== RUN   TestLookupAnimalByID
--- FAIL: TestLookupAnimalByID (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1025bd370]

goroutine 19 [running]:
testing.tRunner.func1.2({0x10266c3e0, 0x1028451f0})
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1632 +0x2c4
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1635 +0x47c
panic({0x10266c3e0?, 0x1028451f0?})
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/panic.go:785 +0x124
gocourse04.TestLookupAnimalByID(0xc0000acb60)
	/Users/Oleksandr_Redko/src/github.com/vikibell/prjctr-golang-beginning/gocourse04/smartzoo_test.go:89 +0x970
testing.tRunner(0xc0000acb60, 0x1026aad38)
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1690 +0x188
created by testing.(*T).Run in goroutine 1
	/opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1743 +0x5e4
FAIL	gocourse04	0.379s
```

2024-08-25 12:39 UTC, alexandear commented on gocourse04/smartzoo_test.go
> +	assert.Equal(t, parrotsSector.ID, sectorFound.ID, "Sectors should be equal")
Щоб пофіксити, треба додати перевірку на `nil`:

```go
if assert.NotNil(t, sectorFound) {
	assert.Equal(t, parrotsSector.ID, sectorFound.ID, "Sectors should be equal")
}
```

Тепер в разі `nil` тест не панікує, а просто зафейлиться:
```
=== RUN   TestLookupAnimalByID
    /Users/Oleksandr_Redko/src/github.com/vikibell/prjctr-golang-beginning/gocourse04/smartzoo_test.go:89:
        	Error Trace:	/Users/Oleksandr_Redko/src/github.com/vikibell/prjctr-golang-beginning/gocourse04/smartzoo_test.go:89
        	Error:      	Expected value not to be nil.
        	Test:       	TestLookupAnimalByID
--- FAIL: TestLookupAnimalByID (0.00s)
FAIL
```

2024-08-25 12:39 UTC, alexandear commented on gocourse04/smartzoo_test.go
> +}
Є варіант використати сабтест [T.Run](https://pkg.go.dev/testing#T.Run) замість двох функцій `TestLookupAnimalByName` та `TestFailLookupAnimalByName`:

```go
func TestLookupAnimalByName(t *testing.T) {
	t.Run("Found", func(t *testing.T) {
		// ...
	})
	t.Run("Not found", func(t *testing.T) {
		// ...
	})}
```

В цьому разі `TestLookupAnimalByName` містить всі тест кейси для перевірки функції `LookupAnimalByName`, їх зазвичай більше, ніж просто "success" та "fail".

2024-08-25 13:16 UTC, vikibell commented on gocourse04/smart_zoo.go
> +	return s, exists
То чи треба нам тут ok чи ні для гетера?

2024-08-25 19:41 UTC, alexandear approved these changes
LGTM

2024-08-26 09:13 UTC, merged