HW-05
vikibell/prjctr-golang-beginning pull request #4
Opened 2024-08-25 18:31 UTC by vikibell

2024-08-27 19:21 UTC, alexandear requested changes

2024-08-27 19:21 UTC, alexandear commented on gocourse05/server.go
> +		fmt.Printf("Sending data \"%s\" to %s", dataToSend, url)
Можна ось так: 
```suggestion
		fmt.Printf("Sending data %q to %s", dataToSend, url)
```

згідно https://pkg.go.dev/fmt

> ```
> %q	a single-quoted character literal safely escaped with Go syntax.
> ```

2024-08-27 19:21 UTC, alexandear commented on gocourse05/server.go
> +func saveProcessedData(p camera.Processor, m *Memory) error {
Напевно ось так має бути правильніше:
```suggestion
func (m *Memory) saveProcessedData(p camera.Processor) error {
```

В пам'яті є метод "зберегти".

2024-08-27 19:21 UTC, alexandear commented on gocourse05/camera/dayCamera_test.go
> +		data, _ := c.retrieveData()
Завжди error треба хендлити.
```suggestion
		data, err := c.retrieveData()
```

Уяви, що хтось перерефакторив `retrieveData` і error тепер став не `nil`. Як тест це задетектить, якщо ігнорити `err`?

2024-08-27 19:21 UTC, alexandear commented on gocourse05/camera/dayCamera_test.go
> +		pd, _ := c.ProcessData()
див. вище:
```suggestion
		pd, err := c.ProcessData()
```

2024-08-27 19:21 UTC, alexandear commented on gocourse05/camera/infraredCamera_test.go
> +		pd, _ := c.ProcessData()
див. вище:
```suggestion
		pd, err := c.ProcessData()
```

2024-08-27 19:21 UTC, alexandear commented on gocourse05/camera/nightCamera_test.go
> +		data, _ := c.retrieveData()
див. вище:
```suggestion
		data, err := c.retrieveData()
```

2024-08-27 19:21 UTC, alexandear commented on gocourse05/camera/nightCamera_test.go
> +		pd, _ := c.ProcessData()
див. вище:
```suggestion
		pd, err := c.ProcessData()
```

2024-08-27 19:21 UTC, alexandear commented on gocourse05/server_test.go
> +	tests := []struct {
📝  класно, використано табличні тест кейси

2024-08-27 19:21 UTC, alexandear commented on gocourse05/server_test.go
> +				url: "test",
в якості `url` можна використовувати `"example.com"`

2024-09-02 14:06 UTC, alexandear requested changes

2024-09-02 14:06 UTC, alexandear commented on gocourse05/camera/camera.go
> +	noLight       = 0
Чи можемо використати `iota`?

https://go.dev/ref/spec#Iota

2024-09-02 14:06 UTC, alexandear commented on gocourse05/server.go
> +}
Пропоную перенести інтерфейс процесора в цей файл і подивитися, як працюватиме:

```suggestion
type Processor interface {
	// ...
}

type Server struct {
	Memory []camera.ProcessedData
	processor Processor
}

func NewServer(processor Processor) *Server {
	// ...
}

func (s *Server) saveProcessedData() error {
	processedData, err := s.processor.ProcessData()
	if err != nil {
		return err
	}

	s.Memory = append(s.Memory, *processedData)

	return nil
}
```

Пояснення тут https://go.dev/wiki/CodeReviewComments#interfaces

2024-09-03 07:50 UTC, vikibell commented on gocourse05/server.go
> +}
Через те, що в різних пакетах камери перестають імплементувати методи, я не дуже розумію як правильно,
зробити все main і все з камери перенести в сервер?Воно якось все ломається з цією зміною.

І для кожної камери свій сервер виходить буде з NewServer то це якось не по завданню і не логічно виходить.

2024-09-03 15:29 UTC, alexandear requested changes

2024-09-03 15:29 UTC, alexandear commented on gocourse05/camera/camera.go
> +	sunLight      = iota
Можна залишити одну `iota`, чи не так?

https://go.dev/wiki/Iota
https://blog.learngoprogramming.com/golang-const-type-enums-iota-bc4befd096d3

2024-09-03 15:29 UTC, alexandear commented on gocourse05/server.go
> +}
[CodeReviewComments#interfaces](https://go.dev/wiki/CodeReviewComments#interfaces) каже:
> Go interfaces generally belong in the package that uses values of the interface type, not the package that implements those values.

Тобто інтерфейси оголошують там, де вони використовуються. В нашому випадку, інтерфейс `Processor` використовується сервером в файлі `server.go`.

Ось цей інтерфейс не дуже правильно оголошений, бо містить неекспортований метод `retrieveData`:
```go
type Processor interface {
	retrieveData() ([]Data, error)
	ProcessData() (*ProcessedData, error)
}

Я пропоную додати інтерфейс в файл `server.go`:

```
type Processor interface {
	ProcessData() (*ProcessedData, error)
}
	
type Server struct {
	// ...
	processor Processor
}
```

Всі камери, які мають метод `ProcessData() (*ProcessedData, error)`, автоматично імплементують цей інтерфейс.

2024-09-03 15:29 UTC, alexandear commented on gocourse05/server_test.go
> +	server := Server{Memory: make([]camera.ProcessedData, 0)}
Краще використовувати окрему змінну `server` для кожного тест кейсу. Тобто перенести всередину `t.Run`. Так не виникне проблем, якщо запустимо тести паралельно через [`t.Parallel()`](https://pkg.go.dev/testing#T.Parallel)

2024-09-08 13:51 UTC, alexandear requested changes

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/day.go
> +			return nil, errors.New("not enought data for processing")
Одруківка:
```suggestion
			return nil, errors.New("not enough data for processing")
```

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/camera.go
> +)
Можна ж по красоті зробити за допомогою кастомного типу https://go.dev/doc/effective_go#constants:
```suggestion
type lightType int

const (
	noLight lightType = iota
	infraredLight
	sunLight
)
```

Також, `noLight == 0` гарно лягає на концепцію ["Make zero value useful"](https://dave.cheney.net/practical-go/presentations/qcon-china.html#_make_the_zero_value_useful).

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/night.go
> +			return nil, errors.New("not enought data for processing")
Одруківка:
```suggestion
			return nil, errors.New("not enough data for processing")
```

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/infrared_test.go
> +package camera
Тести повинні проходити, зараз фейляться:

```
❯ go test -count=1 ./...
ok      gocourse05      0.285s
--- FAIL: TestInfraredCameraRetrieveData (0.00s)
    --- FAIL: TestInfraredCameraRetrieveData/Found (0.00s)
        infrared_test.go:23: RetrieveData() = {ID:1 Animal:Коза_d232536d-883f-485b-8ae7-f7c0e2af9176 Movement:Побігла вліво}
Коза, Побігла вліво; 
--- FAIL: TestNightCameraRetrieveData (0.00s)
    --- FAIL: TestNightCameraRetrieveData/Found (0.00s)
        night_test.go:22: RetrieveData() = {ID:1 Animal:Козаnight Movement:Побігла влівоnight}
FAIL
FAIL    gocourse05/camera       0.457s
FAIL
```

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/infrared_test.go
> +		fmt.Println(pd.AnimalMovement)
Чи потрібен цей рядок в тестах?

В будь-якому разі, для тестів краще використовувати https://pkg.go.dev/testing#T.Log

2024-09-08 13:51 UTC, alexandear commented on gocourse05/server_test.go
> +
📝 зайвий рядок

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/infrared.go
> +	Data      []Data
Пропоную зробити поля неекспортованими для інкапсуляції:
```suggestion
	id        int
	name      string
	data      []Data
```

Для доступу до `id` додати метод `InfraredCamera.ID() int`

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/infrared.go
> +	}
Мені здається, що це нормальна ситуація, коли немає даних. Камера нова, не встигла записати нічого. Точно треба повертати помилку?

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/infrared.go
> +func (ic InfraredCamera) ProcessData() (*ProcessedData, error) {
Здається, так можна спростити код:
```suggestion
func (ic InfraredCamera) ProcessData() (ProcessedData, error) {
```

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/infrared.go
> +		data.Animal = strings.ReplaceAll(re.ReplaceAllString(data.Animal, ""), "_", "")
Здається, переускладнена логіка. Спочатку `Animal = animal + "_" + uuid.NewString()`, а потім через `regexp` видаляється `_ + uuid.NewString()`. Може краще використовувати два поля в структурі: одне для `animal` і одне для `uuid`?

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/day.go
> +		if len(data.Animal) == 0 || len(data.Movement) == 0 {
https://dmitri.shuralyov.com/idiomatic-go#empty-string-check
```suggestion
		if data.Animal == "" || data.Movement == "" {
```

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/day_test.go
> +			t.Errorf("RetrieveData() should not have error: %s", err)
Краще робити [`t.Fatalf`](https://pkg.go.dev/testing#T.Fatalf) замість `t.Errorf`, оскільки немає сенсу перевіряти далі:
```suggestion
			t.Fatalf("RetrieveData() should not have error: %s", err)
```

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/day_test.go
> +		if len(data) == 0 {
Краще явно перевіряти, що очікується рівно 1 елемент в слайсі:
```suggestion
		if len(data) != 1 {
```

Тому що якщо буде 2, то тест спокійно пройде.

2024-09-08 13:51 UTC, alexandear commented on gocourse05/camera/day_test.go
> +		}
Здається, простіше ось так:
```suggestion
		got := data[0]
		want := Data{ID: 1, Animal: "Коза", Movement: "Побігла вліво"}
		if got != want {
			t.Errorf("Unexpected data: got=%+v, want=%+v", got, want)
		}
```

І відповідає
https://go.dev/wiki/CodeReviewComments#useful-test-failures

2024-09-08 15:57 UTC, vikibell commented on gocourse05/camera/infrared.go
> +		data.Animal = strings.ReplaceAll(re.ReplaceAllString(data.Animal, ""), "_", "")
Тут була просто імітація того, що камера може додавати якусь свою інфу, а коли ми процесимо - нам треба прибирати цю інфу.

2024-09-08 16:48 UTC, vikibell commented on gocourse05/camera/infrared.go
> +		data.Animal = strings.ReplaceAll(re.ReplaceAllString(data.Animal, ""), "_", "")
Зробила простіше

2024-09-09 07:33 UTC, alexandear approved these changes
LGTM

2024-09-09 07:38 UTC, merged