HW-06
vikibell/prjctr-golang-beginning pull request #5
Opened 2024-09-01 11:38 UTC by vikibell

2024-09-03 15:11 UTC, alexandear commented on gocourse06/main.go
> +		animals = append(animals, animal)
📝 можна спростити трішки:

```suggestion
	animals := make([]Animal, n)
	for i := range animals {
		animals[i] = Animal{
			ID:     i,
			Health: rand.IntN(100),
			Hunger: rand.IntN(100),
			Mood:   rand.IntN(100),
		}
	}
```

2024-09-03 15:16 UTC, alexandear commented on gocourse06/zoo_test.go
> +func TestRaceConditions(t *testing.T) {
Тестові функції, по суті дублюють код з `main()`. Чи можемо уникнути дублікації?

2024-09-06 13:58 UTC, vikibell commented on gocourse06/zoo_test.go
> +func TestRaceConditions(t *testing.T) {
Можна просто main викликати з тесту?Може є якісь рекомендації?

2024-09-06 14:01 UTC, vikibell commented on gocourse06/zoo.go
> +					e.IsOpen = true
Виправила

2024-09-08 14:11 UTC, alexandear requested changes

2024-09-08 14:11 UTC, alexandear commented on gocourse06/zoo_test.go
> +func TestRaceConditions(t *testing.T) {
Можна створити окрему функцію, яку викликати в `main`. Типу такого:

```go
func main() {
	if err := run(); err != nil {
		fmt.Println(err)
	}
}

func run() error {
	// ...
}

func TestRun() {
	// tests for run()
}
```

2024-09-08 14:11 UTC, alexandear commented on gocourse06/main.go
> +func main() {
Якщо запустити програму через `go run .`, то вона виконується приблизно 6 секунд, з яких 5 секунд нічого не виводиться на екран. Я, як користувач очікую, що програма виводить дані в реальному часі. Затримка може бути максимум 1 секунда.

Пропоную зменшити таймаути до сотень мілісекунд. Можна навіть зробити їх трішки випадковими, типу:

```go
time.Sleep((200 + time.Duration(rand.N(300))) * time.Millisecond)
```

2024-09-08 14:11 UTC, alexandear commented on gocourse06/zoo.go
> +const closeRequest = "close"
У нас реквест може мати два значення, можна спростити:
```suggestion
type request int

const (
	openRequest  request = iota
	closeRequest
)
```

2024-09-15 17:00 UTC, alexandear approved these changes
LGTM

2024-09-15 17:40 UTC, merged