HW-07
vikibell/prjctr-golang-beginning pull request #6
Opened 2024-09-03 09:50 UTC by vikibell

2024-09-03 16:31 UTC, alexandear requested changes

2024-09-03 16:31 UTC, alexandear commented on gocourse07/aviary.go
> +func NewData(ID int, measurement int) Data {
Параметри в функціях завжди з маленької:
```suggestion
func NewData(id int, measurement int) Data {
```

2024-09-03 16:31 UTC, alexandear commented on gocourse07/aviary.go
> +	case <-stopCh:
Чи можемо замінити `stopCh` на контекст? Напевно можемо, прошу доробити на використання `context.Context`.

2024-09-08 14:45 UTC, alexandear requested changes

2024-09-08 14:45 UTC, alexandear commented on gocourse07/aviary.go
> +func measureSensors(sensors []Sensor, dataCh chan<- Data, ctx context.Context, wg *sync.WaitGroup) {
Чомусь ця функція не обробляє `ctx`.

2024-09-08 14:45 UTC, alexandear commented on gocourse07/main.go
> +	return wetnessSensors
📝 можна трішки скоротити назву змінної:

```suggestion
	sensors := make([]Sensor, n)
	for i := range sensors {
		sensors[i] = WetnessSensor{
			ID:      i,
			Wetness: rand.IntN(100),
		}
	}
	return sensors
```

https://go.dev/wiki/CodeReviewComments#variable-names

2024-09-08 14:45 UTC, alexandear commented on gocourse07/main.go
> +
📝 Зайвий рядок:
```suggestion
```

2024-09-08 14:45 UTC, alexandear commented on gocourse07/aviary.go
> +func centralSystem(dataCh <-chan Data, ctx context.Context, wg *sync.WaitGroup) {
Контекст завжди першим параметром має бути, це by convention:
```suggestion
func centralSystem(ctx context.Context, dataCh <-chan Data, wg *sync.WaitGroup) {
```

https://go.dev/wiki/CodeReviewComments#contexts

2024-09-08 14:45 UTC, alexandear commented on gocourse07/main.go
> +	ctx, cancel := context.WithDeadline(context.Background(), deadline)
Це те саме, але простіше:
```suggestion
	ctx, cancel := context.WithTimeout(context.Background(), 100 * time.Millisecond)
```

2024-09-08 14:45 UTC, alexandear commented on gocourse07/main.go
> +	}()
Щось дуже підозріло виглядає, що очікуємо 10 секунд, а потім `wg.Wait()` в окремій горутині, щоб почекати всі інші горутини.

Очікується щось типу такого:
```suggestion
	wg.Wait()
```

2024-09-08 14:45 UTC, alexandear commented on gocourse07/main.go
> +	dataChannel := make(chan Data)
Напевно, можемо зробити канал буферизованим:
```suggestion
	dataChannel := make(chan Data, 4)
```

https://go.dev/doc/effective_go#channels

2024-09-08 14:46 UTC, alexandear commented on gocourse07/aviary.go
> +package main
Здається, цей PR треба мерджити в гілку `main`, а не в `gocourse06`? Ось так зараз:
<img width="465" alt="image" src="https://github.com/user-attachments/assets/c0df3ab8-095c-4dc4-83cc-ea6f8207c5c1">

2024-09-08 14:48 UTC, alexandear commented on gocourse07/aviary.go
> +}
Ось ця функція не сильно покращує код, можна видалити.

2024-09-08 15:06 UTC, vikibell commented on gocourse07/aviary.go
> +package main
Мені так було зручніше, що бачити код домашки 6ої. Так було задумано.

2024-09-09 07:15 UTC, alexandear requested changes

2024-09-09 07:15 UTC, alexandear commented on gocourse07/main.go
> +package main
Для всіх домашок, починаючи з четвертої, обов'язкові тести. 

Для всіх домашок, починаючи з четвертої, обов'язкові тести.

Приклади тестів для конкурентності можна підглянути ось тут:
https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/concurrency
Там взагалі багато різних прикладів, зліва навігація.

2024-09-15 16:58 UTC, alexandear approved these changes
LGTM

2024-09-15 16:58 UTC, alexandear commented on gocourse07/aviary_test.go
> +	want[3] = 10
Компактніше:
```suggestion
	want := []int{0, 20, 40, 10}
```

2024-09-15 17:39 UTC, merged