HW-09
vikibell/prjctr-golang-beginning pull request #7
Opened 2024-09-09 09:52 UTC by vikibell

2024-09-09 12:27 UTC, alexandear requested changes

2024-09-09 12:27 UTC, alexandear commented on gocourse09/main.go
> +package main
Пропоную використати пакети. Ця домашка на SOLID - тут має бути багато різних дизайн структур і відносно мало логіки.

2024-09-15 16:52 UTC, alexandear requested changes

2024-09-15 16:52 UTC, alexandear commented on gocourse09/main.go
> +	z "gocourse09/zone"
Краще не робити еліаси з однієї букви на імпорти:
```suggestion
	"gocourse09/analyzer"
	"gocourse09/feeder"
	"gocourse09/zone"
```

Це погіршує читабельність коду. Це конфліктує з назвами ресіверів, які зазвичай мають одну-дві букви. Це конфліктує з індексними змінними.

2024-09-15 16:52 UTC, alexandear commented on gocourse09/main.go
> +func main() {
Здається, програма дуже мало виводить інформації:
```
❯ go run -race main.go
Poured on gross in amount of 1
Poured on apples in amount of 2
Poured on dry food in amount of 1
```

Це ж симуляція кормушки, яка працює протягом якогось часу. Має точно бути більше даних.

2024-09-15 16:52 UTC, alexandear commented on gocourse09/zone/zone.go
> +	Animals []Animal
А для чого методи `GetAnimals` та `AddAnimals`, якщо клієнт може використати для маніпуляції експортоване поле `Animals`?

Напевно, треба зробити поле приватним?

```suggestion
	animals []Animal
```

2024-09-15 16:52 UTC, alexandear commented on gocourse09/analyzer/analyzer.go
> +		return result
📝 ось так простіше:
```suggestion
	if len(animals) == 0 {
		return Result{}
```

2024-09-15 16:52 UTC, alexandear commented on gocourse09/analyzer/analyzer.go
> +		species[animal.Specie] += 1
```suggestion
		species[animal.Specie]++
```

https://go.dev/ref/spec#IncDec_statements

2024-09-15 16:52 UTC, alexandear commented on gocourse09/feeder/feeder.go
> +	return brackets
Пропущене сортування? Тут `brackets` несортовані.

2024-09-15 16:52 UTC, alexandear commented on gocourse09/feeder/feeder_test.go
> +		}
Можна ж простіше за допомогою пакету `cmp`, як зроблено в `analyzer_test.go`:
```suggestion
		if !cmp.Equal(got, want) {
			t.Errorf("Unexpected data: got=%+v, want=%+v", got, want)
		}
```

2024-09-15 16:52 UTC, alexandear commented on gocourse09/analyzer/analyzer.go
> +type Analyzer interface {
Інтерфейси краще декларувати там, де вони використовуються.

https://medium.com/@mbinjamil/using-interfaces-in-go-the-right-way-99384bc69d39

2024-09-15 18:26 UTC, vikibell commented on gocourse09/analyzer/analyzer.go
> +type Analyzer interface {
Не зрозуміла. Він наче як тут і використовується.

2024-09-15 21:00 UTC, vikibell commented on gocourse09/main.go
> +func main() {
Додала генерацію більшої кількості тварин.

2024-09-15 21:10 UTC, vikibell commented on gocourse09/analyzer/analyzer.go
> +type Analyzer interface {
Наче як мувнула туда де треба

2024-09-16 14:07 UTC, alexandear approved these changes
LGTM

2024-09-16 14:07 UTC, alexandear commented on gocourse09/feeder/feeder.go
> +	sort.Sort(brackets)
📝  В сучасному Go можна відсортувати слайс за допомогою пакетів [`slices`](https://pkg.go.dev/slices) та [`cmp`](https://pkg.go.dev/cmp):
```go
	slices.SortFunc(brackets, func(a, b FoodBracket) int {
		return cmp.Compare(a.Amount, b.Amount)
	})
```

Тип `SortedFoodBrackets` стає непотрібним, можна повертати просто `[]FoodBracket`.

2024-09-16 14:26 UTC, merged